/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContextBox: typeof import('./src/components/common/ContextBox.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftManuBar: typeof import('./src/components/common/LeftManuBar.vue')['default']
    LoginMain: typeof import('./src/components/page/Login/LoginMain.vue')['default']
    NoticeMain: typeof import('./src/components/page/Management/Notice/NoticeMain.vue')['default']
    NoticeModal: typeof import('./src/components/page/Management/Notice/NoticeModal.vue')['default']
    NoticeSearch: typeof import('./src/components/page/Management/Notice/NoticeSearch.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingOrdersDeliveryModal: typeof import('./src/components/page/Trade/ShoppingOrders/ShoppingOrdersDeliveryModal.vue')['default']
    ShoppingOrdersMain: typeof import('./src/components/page/Trade/ShoppingOrders/ShoppingOrdersMain.vue')['default']
    ShoppingOrdersModal: typeof import('./src/components/page/Trade/ShoppingOrders/ShoppingOrdersModal.vue')['default']
    ShoppingOrdersSearch: typeof import('./src/components/page/Trade/ShoppingOrders/ShoppingOrdersSearch.vue')['default']
  }
}
